### ISSUE TITLE
Can we simplified the windows build?

### ISSUE THREAD

**Issue by SteveALee** [GPII/windows#62]
Currently the install instructions include these 2 lines

* npm install --ignore-scripts=true
* grunt build

What is the reason for needing --ignore-scripts?
The docs are a bit hidden but the PR that added it says it just stops prepublish and preinstall scripts running
I see there is no scripts section in the package.json so surely that doesn't matter? Or perhaps just some defaults we need to override?

Can't we add an build or install script to package.json that runs the grunt? Then we simple need to "npm install" as usuall in the node/npm world

**Comment by SteveALee** [comment]
Can someone please delete this - I've moved to jira

**Comment by amb26** [comment]
Issues can't be deleted on github, but anyone including the originator can close them.

**Comment by SteveALee** [comment]
Thanks for closing
